version: '3.8'

services:

  mock-service:
    container_name: mock-service
    image: mock:0.0.1
    network_mode: 'bridge'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=172.17.0.2
      - TEMPLATE=service1.xml
      - QUEUE-WRITE=NEW.RESP