spring.artemis.mode: native
spring.artemis.host: ${HOST:localhost}
spring.artemis.port: ${PORT:61616}
spring.artemis.user: artemis
spring.artemis.password: artemis

jms.queue.read: ${QUEUE-READ:TEST.REQ}
jms.queue.write: ${QUEUE-WRITE:TEST.RESP}
template.name: ${TEMPLATE:testTemplate.xml}