spring.artemis.mode: native
spring.artemis.host: ${HOST:127.0.0.1}
spring.artemis.port: ${PORT:60616}
spring.artemis.user: artemis
spring.artemis.password: artemis

jms.queue.read: TEST.REQ
jms.queue.write: TEST.RESP